parameters:
#    association_activite.example.class: Association\ActiviteBundle\Example

services:
#    association_activite.example:
#        class: %association_activite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
